osx_image: xcode11.3
language: node_js
node_js: "10"
rvm: 2.7.0
jdk: oraclejdk8
install:
  - npm run ci.base.setup
  - npm run ci.pip.install
  - npm run ci.build.ios.setup
before_script: pod repo update
script:
  - fastlane ios build

cache: npm
