before_install:
  - nvm install 10
install:
  - npm run ci.base.setup
  - npm run ci.pip.install

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - .nvm
    - node_modules
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - name: Build Android
      language: android
      os: linux
      jdk: oraclejdk8
      env:
        - BuildAndroid="28"
      script: npm run build.android
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: build/wdio-mobile-utils-demo.apk
        name: Release $TRAVIS_TAG
        on: &on
          tags: true
          branch: master
    - name: Build iOS
      language: objective-c
      os: osx
      osx_image: xcode11.3
      before_script: npm run ci.build.ios.setup
      script: npm run build.ios.sim
      before_deploy: zip -r ${TRAVIS_BUILD_DIR}/build/wdio-mobile-utils-demo.app.zip build/wdio-mobile-utils-demo.app
      skip_cleanup: true
      deploy:
        - provider: script
          script: npm run build.ios
          skip_cleanup: true
          on: *on
        - provider: releases
          api_key: $GITHUB_TOKEN
          skip_cleanup: true
          file_glob: true
          file:
            - build/wdio-mobile-utils-demo.ipa
            - build/wdio-mobile-utils-demo.app.zip
          name: Release $TRAVIS_TAG
          on: *on

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
