language: objective-c
os: osx
osx_image: xcode11.3
jdk: oraclejdk8
before_install:
  - nvm install 10
install:
  - npm run ci.base.setup
  - npm run ci.pip.install
  - npm run ci.build.ios.setup
script:
  - echo "TODO BUILD"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - .nvm
    - node_modules
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: script
    script: bundle exec fastlane ios build
    skip_cleanup: true
    on: &on
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - /build/tns-demo-app.ipa
      - /build/tns-demo-app.apk
      - /build/tns-demo-app.app
    skip_cleanup: true
    on: *on
