language: objective-c
os: osx
osx_image: xcode11.3
jdk: oraclejdk8
before_install:
  - rvm install 2.7.0
  - nvm install 10
install:
  - npm run ci.base.setup
  - npm run ci.pip.install
  - npm run ci.build.ios.setup
script:
  - bundle exec fastlane ios build

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - .nvm
    - node_modules
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
