language: objective-c
os: osx
osx_image: xcode11.3
jdk: oraclejdk8
before_install:
  - rvm install 2.7.0
  - nvm install 10
install:
  - npm run ci.base.setup
  - npm run ci.pip.install
  - npm run ci.build.ios.setup
  - sudo gem install xcodeproj
  - sudo gem install cocoapods
  - pod setup
script:
  - tns doctor
  - fastlane ios build

cache: npm
