setup_travis
fastlane_version '2.142.0'

platform :ios do

desc 'Fetch certificates and provisioning profiles'
lane :certificates do
    match(type: 'development')
end

desc 'Build the iOS application.'
lane :build do
    signing_type = "development"
    path_xcodeproj = './platforms/ios/tnsdemoapp.xcodeproj'
    path_xcworkspace = './platforms/ios/tnsdemoapp.xcworkspace'
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

    sh("tns", "prepare", "ios", "--release", "--clean", "--env.production", "--env.aot", "--env.uglify")

    match(type: signing_type, readonly: true)

    disable_automatic_code_signing(
      path: path_xcodeproj
    )

    build_app(
      scheme: "tnsdemoapp",
      workspace: path_xcworkspace,
      export_method: signing_type,
      output_directory: "./build",
      output_name: "tns-demo-app",
      xcargs: {
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_#{app_identifier}_#{signing_type}"]
      }
    )
end

end
