setup_travis
fastlane_version '2.142.0'

platform :ios do

desc 'Fetch certificates and provisioning profiles'
lane :certificates do
    match(type: 'development')
end

desc 'Build the iOS application.'
lane :build do
    sh("tns", "prepare", "ios", "--release", "--clean", "--env.production", "--env.aot", "--env.uglify")

    match(type: "development", readonly: true)

    disable_automatic_code_signing(
      path: './platforms/ios/tnsdemoapp.xcodeproj'
    )

    build_app(
      scheme: "tnsdemoapp",
      workspace: './platforms/ios/tnsdemoapp.xcworkspace',
      export_method: "development",
      output_directory: "./build",
      output_name: "tns-demo-app"
      xcargs: {
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_#{ENV['APP_IDENTIFIER']}_#{signing_type}"]
      }
    )
end

end
